spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localdb
    username: root
    password: K59785978@m

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: false
    drop-first: false
    change-log: liquibase/changelog.xml


server:
  servlet:
    context-path: /mds
  port: ${PORT:8080}

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

